### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by karayamanemre** [Sajeelzafar/to-do-list#5]
Good job @Sajeelzafar 👏🏽 
Your project is functional and useful. Kudos for the modularity. 👍🏽 
There are a few suggestions we think can improve your app.
- You can improve the design to make it more visually appealing. 
- You can reduce the redundancy on this [part](https://github.com/Sajeelzafar/to-do-list/blob/270887f1e86169d141c97311786e884fd46984d2/src/index.js#L20-L24).

**Comment by Sajeelzafar** [comment]
Thank you for the suggestions. I have removed the redundancy on that part and some others as well. I have worked on styling as well.
